### ISSUE TITLE
Scraper not working when when Parsing Games Linux

### ISSUE THREAD

**Issue by jes-moore** [HarryShomer/Hockey-Scraper#10]
Heyo- first off thanks for the package!

I'm having issues with a relatively simple function call. I'm running 3.6 on linux (ubuntu 18.04). Any help would be great, let me know if you need any more info.

```python
import hockey_scraper

# Scrapes all games between 2016-10-10 and 2016-10-20 without shifts and stores the data in a Csv file
hockey_scraper.scrape_date_range('2016-10-10', '2016-10-20', False)`
```
```python
Scraping Game  2016020001 2016-10-12
Traceback (most recent call last):

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-24-43f5db1c1b18>", line 4, in <module>
    hockey_scraper.scrape_date_range('2016-10-10', '2016-10-20', False)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/scrape_functions.py", line 179, in scrape_date_range
    pbp_df, shifts_df = scrape_list_of_games(games, if_scrape_shifts)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/scrape_functions.py", line 128, in scrape_list_of_games
    pbp_df, shifts_df = game_scraper.scrape_game(str(game["game_id"]), game["date"], if_scrape_shifts)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/game_scraper.py", line 351, in scrape_game
    pbp_df = scrape_pbp(game_id, date, roster, game_json, players, teams)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/game_scraper.py", line 272, in scrape_pbp
    html_df = html_pbp.scrape_game(game_id, players, teams)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/html_pbp.py", line 841, in scrape_game
    return scrape_pbp(game_html, game_id, players, teams)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/html_pbp.py", line 802, in scrape_pbp
    cleaned_html = clean_html_pbp(game_html)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/html_pbp.py", line 133, in clean_html_pbp
    soup = get_soup(html)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/hockey_scraper/html_pbp.py", line 68, in get_soup
    soup = soup.select('td.+.bborder')

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/bs4/element.py", line 1377, in select
    return soupsieve.select(selector, self, namespaces, limit, **kwargs)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/soupsieve/__init__.py", line 108, in select
    return compile(select, namespaces, flags).select(tag, limit)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/soupsieve/__init__.py", line 59, in compile
    return cp._cached_css_compile(pattern, namespaces, flags)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/soupsieve/css_parser.py", line 178, in _cached_css_compile
    CSSParser(pattern, flags).process_selectors(),

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/soupsieve/css_parser.py", line 810, in process_selectors
    return self.parse_selectors(self.selector_iter(self.pattern), index, flags)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/soupsieve/css_parser.py", line 688, in parse_selectors
    key, m = next(iselector)

  File "/home/jmoore/tensorflow/lib/python3.6/site-packages/soupsieve/css_parser.py", line 797, in selector_iter
    raise SyntaxError("Invlaid character {!r} at position {}".format(pattern[index], index))

  File "<string>", line unknown
SyntaxError: Invlaid character '.' at position 2
```

**Comment by jes-moore** [comment]
> @jes-moore I'm having trouble reproducing this error. Can you let me know what version of bs4 you are using?
I'm using bs4 0.0.1. I think @facelessuser is correct, but the select_all worked well for me so I left it as is as I'm not very experienced with BeautifulSoup

**Comment by HarryShomer** [comment]
@facelessuser Thanks for your help

@frutoper Sorry I'm late on this. I just fixed the line @facelessuser noted and pushed the change to the  master branch. So check the last commit. If the problem still persists let me know. Otherwise please close the issue.

**Comment by HarryShomer** [comment]
Going to close this. Feel free to reopen it if it's still an issue.
