### ISSUE TITLE
ModuleNotFoundError: No module named 'hockey_scraper.nwhl'

### ISSUE THREAD

**Issue by Btibert3** [HarryShomer/Hockey-Scraper#11]
I just pip-installed into a clean python 3.7 environment created with conda, and got the following error on import:

```
ModuleNotFoundError: No module named 'hockey_scraper.nwhl'
```

**Comment by mcbarlowe** [comment]
I have duplicated this error on Mac OS X Mojave with python 3.6.5 using a VirtualEnvWrapper
Here is the full trace report 
```
Traceback (most recent call last):
  File "nwhltest.py", line 1, in <module>
    import hockey_scraper
  File "/Users/MattBarlowe/.virtualenvs/hockeyscrapertest/lib/python3.6/site-packages/hockey_scraper/__init__.py", line 1, in <module>
    import hockey_scraper.nwhl.scrape_functions as nwhl
ModuleNotFoundError: No module named 'hockey_scraper.nwhl'
```

**Comment by mhbw** [comment]
also got the same error...

**Comment by mattdonders** [comment]
Here are my findings with verbose mode. I haven't found anything on Google, but I wonder if doing `import hockey_scraper.nwhl.scrape_functions as nwhl` is allowed in the top-level `__init__.py` file.

```
>>> import hockey_scraper
# /home/mattdonders/Development/python/hockeyscrapertest/venv/lib/python3.6/site-packages/hockey_scraper/__pycache__/__init__.cpython-36.pyc matches /home/mattdonders/Development/python/hockeyscrapertest/venv/lib/python3.6/site-packages/hockey_scraper/__init__.py
# code object from '/home/mattdonders/Development/python/hockeyscrapertest/venv/lib/python3.6/site-packages/hockey_scraper/__pycache__/__init__.cpython-36.pyc'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mattdonders/Development/python/hockeyscrapertest/venv/lib/python3.6/site-packages/hockey_scraper/__init__.py", line 1, in <module>
    import hockey_scraper.nwhl.scrape_functions as nwhl
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'hockey_scraper.nwhl'
```

**Comment by HarryShomer** [comment]
@Btibert3 Try reinstalling the package (1.32.3). Just tested it and it works fine in my test environment. I'll close this once I get another confirmation that it's fixed. 

Issue was with specifying sub-packages in the setup.py. You have to specify for the package to look for them. Otherwise what ends up happening is when you build the package using `python setup.py sdist bdist_wheel` the resulting source code distribution won't look for those sub-packages (so it was just an __init__.py). 

![Screen Shot 2019-05-15 at 1 35 24 PM](https://user-images.githubusercontent.com/25351167/57796629-9be56a00-7716-11e9-8170-b45394b1c222.png)

**Comment by mcbarlowe** [comment]
I have successfully installed the package without `ModuleNotFoundError` however now encountering a new bug will open new ticket

**Comment by Btibert3** [comment]
Thanks, the issue related to this ticket works on my side.  Thanks for hopping on this so fast @HarryShomer
