### ISSUE TITLE
nwhl.scrape_games not pulling data

### ISSUE THREAD

**Issue by mcbarlowe** [HarryShomer/Hockey-Scraper#12]
Working in clean environment with only `hockey_scraper` and dependent packages installed. 
Just using the README commands. Am at work so if you want to hold off until I can duplicate this at home feel free.
```
Python 3.7.2 (default, Feb 12 2019, 08:15:36)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import hockey_scraper
>>> hockey_scraper.nwhl.scrape_games([14694271, 14814946, 14689491], docs_dir='/Users/mcbarlowe/')
Scraping NWHL Game  14694271
Json pbp for game 14694271 is either not there or can't be obtained
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mbarlowe/code/python/pyenvs/hockey_scrape/lib/python3.7/site-packages/hockey_scraper/nwhl/scrape_functions.py", line 83, in scrape_games
    pbp_df = scrape_list_of_games(games)
  File "/Users/mbarlowe/code/python/pyenvs/hockey_scrape/lib/python3.7/site-packages/hockey_scraper/nwhl/scrape_functions.py", line 52, in scrape_list_of_games
    if not pbp_df.empty:
AttributeError: 'NoneType' object has no attribute 'empty'
```

**Comment by HarryShomer** [comment]
Just tried it out and worked fine. Probably just random. Have you tried again?

Either way the error was was due to function `nwhl.json_pbp.scrape_game`. On error it mistakenly returned `None` instead of an empty DataFrame. Just fixed it

**Comment by mcbarlowe** [comment]
Closing this as I think it was due to firewall at work as it works fine right now at home and I cannot duplicate
