### ISSUE TITLE
json_schedule endpoint appears to be broken

### ISSUE THREAD

**Issue by RRC92193** [HarryShomer/Hockey-Scraper#34]
Is anyone else having issues with the endpoint in the json_schedule ? Seems to be returning no data for me when I try to use hockey_scraper.scrape_games or hockey_scraper.scrape_seasons. 

code is pretty simple. 

```
import hockey_scraper

hockey_scraper.scrape_games([2023020506], True)

```
Throwing me this error. 

Traceback (most recent call last):
  File "/home/hugo/dev/hockey/src/hockey-scraper/scrape_game.py", line 3, in <module>
    hockey_scraper.scrape_games([2023020506], True)
  File "/home/hugo/dev/hockey/src/hockey_venv/lib/python3.10/site-packages/hockey_scraper/nhl/scrape_functions.py", line 237, in scrape_games
    games_list = json_schedule.get_dates(games)
  File "/home/hugo/dev/hockey/src/hockey_venv/lib/python3.10/site-packages/hockey_scraper/nhl/json_schedule.py", line 90, in get_dates
    schedule = scrape_schedule(date_from, date_to, preseason=True, not_over=True)
  File "/home/hugo/dev/hockey/src/hockey_venv/lib/python3.10/site-packages/hockey_scraper/nhl/json_schedule.py", line 114, in scrape_schedule
    schedule_json = chunk_schedule_calls(date_from, date_to)
  File "/home/hugo/dev/hockey/src/hockey_venv/lib/python3.10/site-packages/hockey_scraper/nhl/json_schedule.py", line 56, in chunk_schedule_calls
    chunk_sched = get_schedule(f_chunk, t_chunk)
  File "/home/hugo/dev/hockey/src/hockey_venv/lib/python3.10/site-packages/hockey_scraper/nhl/json_schedule.py", line 31, in get_schedule
    return json.loads(shared.get_file(page_info, force=True))
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

**Comment by HarryShomer** [comment]
Hey,

It's fixed now.

Regards,
Harry
